### ISSUE TITLE
google colab

### ISSUE THREAD

**Issue by ghost** [mchong6/GANsNRoses#2]
great job, please make a google colab for inference

**Comment by mchong6** [comment]
I've added colab. This is my first time putting something up on colab so let me know if anything breaks!

**Comment by seecswajid** [comment]
ImportError: No module named 'fused'

I tried "!pip install fuse-python" but it is not installing

**Comment by mchong6** [comment]
For some reason colab cant run the custom cuda extensions. So I have a separate branch called colab that implements everything in native pytorch. There should be a line in colab that switches to that branch. Everything should run properly after that.

**Comment by ghost** [comment]
@mchong6 thanks is it possible to do inference on cpu?

**Comment by mchong6** [comment]
added a flag in colab to allow inference on cpu.

**Comment by ghost** [comment]
thanks!

**Comment by AK391** [comment]
@mchong6 I am trying to convert the torch tensor back to a pil image, getting a result like this

 fake_A2B = G_A2B.decode(A2B_content.repeat(num_styles,1,1,1), style)
 tensor_to_pil = transforms.ToPILImage()(fake_A2B.squeeze_(0))

<img width="770" alt="Screen Shot 2021-06-15 at 3 15 13 PM" src="https://user-images.githubusercontent.com/81195143/122110591-b6eea080-cdec-11eb-8e01-7d59069a8f07.png">

**Comment by AK391** [comment]
@mchong6 got it working
std=(0.5, 0.5, 0.5)
mean=(0.5, 0.5, 0.5)
z = fake_A2B * torch.tensor(std).view(3, 1, 1)
z = z + torch.tensor(mean).view(3, 1, 1)
tensor_to_pil = transforms.ToPILImage(mode='RGB')(z.squeeze())
