### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by LeRoii** [mchong6/GANsNRoses#20]
hello,
It seems that it takes a huge amount of memory to train this network, 
first I tried to train this network on 2080Ti with 12GB memory, it always crashed and said CUDA out of memory error,
then I tried on v100 and it worked. It takes about 17GB memory  to train this network, is it too much?

**Comment by mchong6** [comment]
Yea it is pretty memory intensive. What you can try is reducing the number of channels of the conv layers  https://github.com/mchong6/GANsNRoses/blob/414e9e77c3df47d4ecf7941b5dcfdffec67403ee/model.py#L16
 
or maybe change the architecture.
