### ISSUE TITLE
about choosing latent dimension

### ISSUE THREAD

**Issue by LeeDongYeun** [mchong6/GANsNRoses#23]
Hi, thanks for your great work!

I have a question about the latent dimension setting.
Is there any specific reason to choose latent dimension to 8?

The base setting of stylegan's latent dimension is 512. 
And in just my opinion, dimension 8 is not enough to embed style.
Could you explain why you set it up like that?

**Comment by mchong6** [comment]
I followed the setting used in MUNIT. I haven't tried with higher dimension counts but potentially if the latent dimension is too high, the style code might encode "too much information" and may lead to content code being ignored.

**Comment by LeeDongYeun** [comment]
Thanks for reply!!! :)
