### ISSUE TITLE
Full model for transfer learning?

### ISSUE THREAD

**Issue by arfafax** [mchong6/GANsNRoses#6]
The model released in the notebook is only 300MB and seems to only include the final A2B and B2A ema generators, so it can only be used for inference.

Is it possible to get ahold of a full pretrained checkpoint for fine tuning/transfer learning? Retraining from scratch will take several weeks on my hardware.

**Comment by mchong6** [comment]
Will do, upload by tomorrow probably.

**Comment by mchong6** [comment]
added to README.
