### ISSUE TITLE
Only for girls?

### ISSUE THREAD

**Issue by DWCTOD** [mchong6/GANsNRoses#8]
Thanks share your greate work!
When I try  input a man's image, the result is :
![image](https://user-images.githubusercontent.com/41478810/122720213-c4e76a00-d2a1-11eb-9957-c87db1076992.png)
So, this olny for girls?

**Comment by mchong6** [comment]
Yes this is trained with selfie2anime dataset from UGATIT which only has females. A better training is needed to generalize better.

**Comment by tsaiggo** [comment]
haha, hope it can support man's image
